[package]
name = "matterdb"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Persistent storage implementation based on RocksDB"
readme = "README.md"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
rocksdb.workspace = true
serde = { workspace = true, features = ["derive"] }
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
matterdb-derive.workspace = true

assert_matches.workspace = true
bincode = { workspace = true, features = ["derive"] }
criterion.workspace = true
modifier.workspace = true
proptest.workspace = true
rand.workspace = true
rand_xorshift.workspace = true
url.workspace = true
tempfile.workspace = true
version-sync.workspace = true

[[bench]]
name = "criterion"
path = "benches/lib.rs"
harness = false

[lints]
workspace = true
